%use the get_Data_CMIP7 function to actually produce necessary .txt files
%for new scenarios
T = readtable( ...
    'continuous_emissions_timeseries_1750_2500.csv', ...
    'Delimiter', ',', ...
    'ReadVariableNames', true);

T.Properties.VariableNames(1:10)


%%

GetScenario(T,...
    "REMIND-MAgPIE 3.5-4.11",...
    "SSP1 - Very Low Emissions",...
    "SSP1");

GetScenario(T,...
    "IMAGE 3.4",...
    "SSP2 - Medium Emissions",...
    "SSP2");

GetScenario(T,...
    "GCAM 8s",...
    "SSP3 - High Emissions",...
    "SSP3");